### ISSUE TITLE
关于RLS去混响算法的问题

### ISSUE THREAD

**Issue by Sally-wow** [helianvine/adaptive-dereverberation#1]
请问能否看一下您写的实现RLS去混响的Matlab算法代码？最近在研究相关方向的问题，我想借鉴学习一下。
如果可以的您可以将代码发到我的邮箱：sunshuaiheng123@163.com。  非常感谢！

**Comment by helianvine** [comment]
> 请问能否看一下您写的实现RLS去混响的Matlab算法代码？最近在研究相关方向的问题，我想借鉴学习一下。
> 如果可以的您可以将代码发到我的邮箱：[sunshuaiheng123@163.com](mailto:sunshuaiheng123@163.com)。 非常感谢！

不好意思，代码暂时没有开源计划。如果在实现时遇到任何问题，欢迎与我讨论。

**Comment by Sally-wow** [comment]
> > 请问能否看一下您写的实现RLS去混响的Matlab算法代码？最近在研究相关方向的问题，我想借鉴学习一下。
> > 如果可以的您可以将代码发到我的邮箱：[sunshuaiheng123@163.com](mailto:sunshuaiheng123@163.com)。 非常感谢！
> 
> 不好意思，代码暂时没有开源计划。如果在实现时遇到任何问题，欢迎与我讨论。

感谢您的回应。我还想请教您一些问题： 我实现了代码后，在matlab的仿真中对比了滤波器预测阶数为40和10时的去混响效果，却发现阶数40的输出结果反而没有阶数为10的效果好，并且滤波器阶数过大时算法的运行速度也会非常慢。想请教您一下可能是什么原因导致的？
